name: media-server-unit-tests

on:
  push:
    #branches: [ master ]
  pull_request:
    #branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: 'recursive'
    - run: pwd
    - run: ls -l ./
    - run: ls ./ext/googletest/
    - run: ls ./ext/libdatachannels
    - name: Initialize submodules
      run: git submodule update --init --recursive
    - name: Configure
      run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release ..
    - name: make
      run: cd build && make
    - name: Run Test
      run: cd build && ./MediaServerUnitTest
